version: "3.7"
services:

  webpack:
    build:
      context: ./docker/node
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      TSC_WATCHFILE: UseFsEvents
      NODE_OPTIONS: --max_old_space_size=4096
    command: [npm, run, dev]
    ports:
      - 9000:9000

  node:
    build:
      context: ./docker/node
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      TSC_WATCHFILE: UseFsEvents
      NODE_OPTIONS: --max_old_space_size=4096
    tty: true